apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      schedulerName: hybrid-scheduler
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
