apiVersion: v1
kind: ServiceAccount
metadata:
  name: hybrid-scheduler-account
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hybrid-scheduler-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hybrid-scheduler-cluster-role-binding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: hybrid-scheduler-account
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: hybrid-scheduler-cluster-role
  apiGroup: rbac.authorization.k8s.io
